export const FontSize = [
  { value: 12, label: '12px' },
  { value: 14, label: '14px' },
  { value: 16, label: '16px' },
  { value: 18, label: '18px' },
  { value: 20, label: '20px' },
  { value: 22, label: '22px' },
  { value: 24, label: '24px' },
  { value: 26, label: '26px' },
  { value: 28, label: '28px' },
  { value: 30, label: '30px' },
  { value: 32, label: '32px' },
]

export const PredefineColors = ['#ff4500', '#ff8c00', '#ffd700', '#90ee90', '#00ced1', '#1e90ff', '#c71585', 'rgba(255, 69, 0, 0.68)', 'rgb(255, 120, 0)', 'hsv(51, 100, 98)', 'hsva(120, 40, 94, 0.5)', 'hsl(181, 100%, 37%)', 'hsla(209, 100%, 56%, 0.73)', '#c7158577']

export const FontFamily = [
  'Arial, helvetica, sans-serif',
  'Georgia, serif',
  'Impact, Charcoal, sans-serif',
  'Tahoma, Geneva, sans-serif',
  'Verdana, Geneva, sans-serif',
  'Courier New, Courier, monospace',
  'Lucida Console, Monaco, monospace',
  'Comic Sans MS, cursive, sans-serif',
  'Times New Roman, Times, serif',
  'Trebuchet MS, Helvetica, sans-serif',
  'Palatino Linotype, Book Antiqua, Palatino, serif',
  'Arial Black, Gadget, sans-serif',
  'Bookman Old Style, Bookman, serif',
  'Century Gothic, sans-serif',
  'Garamond, serif',
  'Lucida Sans Unicode, Lucida Grande, sans-serif',
  'MS Serif, New York, serif',
  'MS Sans Serif, Geneva, sans-serif',
  'Symbol, sans-serif',
  'Wingdings, Zapf Dingbats, sans-serif',
  'Webdings, sans-serif',
  'Copperplate, Copperplate Gothic Light, sans-serif',
  'Papyrus, fantasy',
  'Brush Script MT, Brush Script Std, cursive',
]

export const PreStyle = {
  node: [
    {
      fill: 'rgb(231,253,250)',
      stroke: 'rgb(149, 231, 226)',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#e7f7fe',
      stroke: '#b2defe',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#fef7e7',
      stroke: '#fedcab',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#f8f0fe',
      stroke: '#d7bdf4',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: 'rgb(255, 218, 218)',
      stroke: 'rgb(247, 155, 155)',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#fbfbca',
      stroke: '#f7f71c',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#7EA6E0',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#FFCE9F',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#A9C4EB',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#DFEFCA',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#D1F5FF',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#D4AEF9',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#80beaf',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#b3ddd1',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#d1dce2',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#f58994',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#ee9c6c',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#86e3ce',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#d0e6a5',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#ffdd94',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#fa897b',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#ccabd8',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#60efdb',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#bef2e5',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#c5e7f1',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#79ceed',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#6f89a2',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },

    {
      fill: '#dea3dc',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#f7db70',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#eabebf',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#75cce8',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#a5dee5',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#5d7599',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#abb6c8',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#dadada',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#f7f0c6',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#c2c4b6',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#478ba2',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#de5b6d',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#e9765b',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#f2a490',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
    {
      fill: '#b9d4db',
      stroke: '#333',
      textFill: '#333',
      strokeWidth: 2,
    },
  ],
  group: [
    {
      headStyle: {
        fill: '#F1ECAA',
        stroke: '#333',
        textFill: '#333',
        textPosition: 'insideLeft',
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: 'normal',
      },
      groupStyle: {
        fill: '#F0BABA',
        stroke: '#333',
      },
    },
    {
      headStyle: {
        fill: '#FD9973',
        stroke: '#333',
        textFill: '#333',
        textPosition: 'insideLeft',
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: 'normal',
      },
      groupStyle: {
        fill: '#5AC39D',
        stroke: '#333',
      },
    },
    {
      headStyle: {
        fill: '#5AB978',
        stroke: '#333',
        textFill: '#333',
        textPosition: 'insideLeft',
        fontSize: 14,
        fontStyle: 'normal',
        fontWeight: 'normal',
      },
      groupStyle: {
        fill: '#DD727F',
        stroke: '#333',
      },
    },
  ],
}

export const StrokeWidth = [
  { value: 1, label: '1px' },
  { value: 2, label: '2px' },
  { value: 3, label: '3px' },
  { value: 4, label: '4px' },
  { value: 5, label: '5px' },
  { value: 6, label: '6px' },
  { value: 7, label: '7px' },
  { value: 8, label: '8px' },
  { value: 9, label: '9px' },
  { value: 10, label: '10px' },
]
