# 1 工作流名称  
name: CI  

# 2 工作流执行名称  
run-name: ${{ github.actor }} is updating repo, starting build...  

# 3 触发器  
on:  
  # push 推送  
  push:  
    branches: ["main"]  # 通常主分支命名为 main  
  # PR 合并提交  
  pull_request:  
    branches: ["main"]  

  # 允许您从“操作”选项卡手动运行此工作流  
  workflow_dispatch:  

# 4 设置权限（文件是可以被读写修改的）  
permissions:  
  contents: write  

# 工作1  
jobs:  
  # 任务名称  
  build:  
    # 执行平台  
    runs-on: ubuntu-latest  

    # 任务步骤  
    steps:  
      # 1 将代码仓库的内容拉取（或称为检出）到工作目录中  
      - name: Checkout code (检出代码)  
        uses: actions/checkout@v3  
      # 2 安装 Node.js 环境，并设置版本  
      - name: Setup Node.js (设置 Node 版本)  
        uses: actions/setup-node@v3  
        with:  
          node-version: 14.21.3  
      # # 3 安装 npm  
      # - name: Install npm (安装 npm)  
      #   run: npm install -g npm@7.0.0  # 使用 npm 命令而不是 npm/action-setup  

      # 4 安装依赖  
      - name: Install dependencies (安装依赖)  
        run: npm install  

      # 5 代码检查（可选）  
      # - name: lint (代码检查)  
      #   run: npm run lint  

      # 6 跑测试（可选）  
      # - name: Test (测试)  
      #   run: npm run test  

      # 7 构建项目  
      - name: Build (构建)  
        run: npm run build  

      # 8 处理构建产物（如果要发布到 GitHub Pages）  
      - name: Upload build artifacts (上传构建产物)  
        uses: actions/upload-pages-artifact@v2  
        with:  
          path: "./dist"  

      # 9 部署到 GitHub Pages  
      - name: Deploy to GitHub Pages (部署到 GitHub Pages)  
        uses: actions/deploy-pages@v1